http {
    include mime.types;

    server{
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;

        }

        location /upload {
            proxy_pass http://app:8000/upload;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            }

        location /images-list {
            alias /usr/share/nginx/html/static;
            index images-list.html;

            }
        location /api/images-list {
            proxy_pass http://app:8000/api/images-list;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            }

        location /all_images {
            alias /usr/share/nginx/html/static;
            index all_images.html;

            }

        location /api/all_images {
            proxy_pass http://app:8000/api/all_images;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            }

        location ~ ^/api/delete/(?<id>[0-9]+)$ {
            limit_except GET POST DELETE {
               deny all;
            }
            proxy_pass http://app:8000/api/delete/$id;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Отдача изображений через Nginx
        location ~ /images/.*.(gif|jpg|png|jpeg)$ {
            root /usr/share/nginx;  # Указываем корень, чтобы путь был /usr/share/nginx/images/
            try_files $uri =404;
        }


        location /favicon.ico {
            alias /usr/share/nginx/html/;
            }
        }
        }

events{}
